### ISSUE TITLE
Erreur de syntaxe en section 1.1.4 Problématique connue

### ISSUE THREAD

**Issue by fmacary** [ansforge/IG-fhir-mesures-de-sante#116]
Texte actuel : 
Les profils mesures de santé sont optionnellement liés à un device qui **doivent** hériter du profil PHD (Personal Health Device), couvrant uniquement les appareils personnels connectés.
Correction proposée : 
Les profils mesures de santé sont optionnellement liés à un device qui **doit** hériter du profil PHD (Personal Health Device), couvrant uniquement les appareils personnels connectés.

**Comment by nriss** [comment]
Merci pour ton retour! PR faite :)
