### ISSUE TITLE
Erreur de JDV pour l'exemple BODYWEIGHT

### ISSUE THREAD

**Issue by TristanKEREVAL** [ansforge/IG-fhir-mesures-de-sante#51]
Le code utilisé dans l'exemple (https://interop.esante.gouv.fr/ig/fhir/mesures/Observation-ExampleMesFrObservationBodyWeight001.json.html) n'est pas présent dans le JDV bindé (Required).

TRE référencée dans l'exemple : https://mos.esante.gouv.fr/NOS/TRE_R306-CLADIMED/FHIR/TRE-R306-CLADIMED
Code utilisé dans l'exemple : K50BI02

JDV bindé dans la SD : https://mos.esante.gouv.fr/NOS/JDV_J145-MethodBodyWeight-ENS/FHIR/JDV-J145-MethodBodyWeight-ENS

**Comment by nriss** [comment]
Cf https://github.com/ansforge/IG-fhir-mesures-de-sante/issues/50
