### ISSUE TITLE
Absence de binding dans extension

### ISSUE THREAD

**Issue by TristanKEREVAL** [ansforge/IG-fhir-mesures-de-sante#52]
Pourquoi les binding sur la value de l’extension https://interop.esante.gouv.fr/ig/fhir/mesures/StructureDefinition-mesures-number-of-days.html n’est pas présent directement dans la SD de l’extension ? Cette contrainte est pour l'instant présente dans la SD dans la seul SD utilisant cette extension (https://interop.esante.gouv.fr/ig/fhir/mesures/StructureDefinition-mesures-observation-glucose.html).
Est ce que c'est pour plus tard, la rendre réutilisable pour d'autres profils et d'autres jdv ?

**Comment by nicolasArnoux** [comment]
Oui, c'était pour cette raison.
