### ISSUE TITLE
Question Fonctionnement Pattern

### ISSUE THREAD

**Issue by TristanKEREVAL** [ansforge/IG-fhir-mesures-de-sante#53]
On ne comprend pas le fonctionnement de la contrainte de pattern sur cet attribut. C'est le code=1 qui est propre à l'unité de mesure de douleur c'est bien ça ? Car dans les autres profils la valeur est fixée, ça ne passe pas par une contrainte de pattern.
https://interop.esante.gouv.fr/ig/fhir/mesures/StructureDefinition-mesures-observation-pain-severity-definitions.html#Observation.value[x]:valueQuantity.code

**Comment by nriss** [comment]
Peux-tu mettre une capture d'écran ? Je ne vois pas de quel slicing tu parles

**Comment by TristanKEREVAL** [comment]
![image](https://github.com/ansforge/IG-fhir-mesures-de-sante/assets/122813625/f638d41d-5f74-4b46-bd0e-ffa2ebbc3e3b)

**Comment by nriss** [comment]
Tu trouveras la description ici de pattern et fixed : https://www.hl7.org/fhir/R4/elementdefinition-definitions.html#ElementDefinition.fixed_x_
