### ISSUE TITLE
Problème de binding de CodeableConcept vers des SD et non des JDV

### ISSUE THREAD

**Issue by TristanKEREVAL** [ansforge/IG-fhir-mesures-de-sante#54]
Certains attributs de type CodeableConcept sont bindés vers des StructureDefinition et non des ValueSet, est ce que c'est normal ?
Exemple : Sur tout les attributs : Observation.interpretation (https://interop.esante.gouv.fr/ig/fhir/mesures/StructureDefinition-mesures-fr-observation-heartrate.html
https://interop.esante.gouv.fr/ig/fhir/mesures/StructureDefinition-mesures-fr-observation-bp.html
https://interop.esante.gouv.fr/ig/fhir/mesures/StructureDefinition-mesures-fr-observation-body-temperature.html
https://interop.esante.gouv.fr/ig/fhir/mesures/StructureDefinition-mesures-fr-observation-bodyheight.html
https://interop.esante.gouv.fr/ig/fhir/mesures/StructureDefinition-mesures-fr-observation-body-weight.html)

Pour les autres profils c'est bien bindé vers un jdv d'HL7 (http://hl7.org/fhir/R4/valueset-observation-interpretation.html)

**Comment by nriss** [comment]
Le problème vient des profils d'InteropSanté à priori : https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0/files/783572/~overview

Que penses-tu de mettre le binding du valueset HL7 @nicolasArnoux  ?
