### ISSUE TITLE
Jeu de valeurs de l'extension "type de diabète"

### ISSUE THREAD

**Issue by fmacary** [ansforge/IG-fhir-mesures-de-sante#62]
Je suis surpris de découvrir un jeu de valeurs de codes CIM-10 dans l'extension MesDiabetisType. La CIM-10 n'est pas une terminologie clinique, or c'est ce qu'il faudrait ici. Je suppose que ce jeu de valeurs va migrer vers la terminologie clinique SNOMED CT maintenant que la France l'adopte.

**Comment by nriss** [comment]
Hello François, merci pour ton commentaire! Après discussions avec les experts, la CIM-10 est déjà en place sur ce sujet et sera, à terme, remplacée par la CIM-11. L'objectif est de conserver ce qui est en place en France pour ne pas impacter l'écosystème avec des changements réguliers de Terminologie. La SNOMED CT permettra de couvrir des cas d'usages qui ne sont pas actuellement traités par d'autres Terminologies en France.

Je clos l'issue :)
